package com.syukron.dinopedia

object DinosData {
    private val dinoNames = arrayOf("Ornithomimus",
        "Oviraptor",
        "Rinchenia",
        "Saurolophus",
        "Spinosaurus",
        "Stegosaurus",
        "Therizinosaurus",
        "Troodon",
        "Tyrannosaurus",
        "Velociraptor")

    private val dinoDetails = arrayOf("Ornithomimus adalah dinosaurus mirip burung unta. Tubuhnya tanpa bulu, berkaki langsing, kepala kecil,  dan leher panjang. Ornithomimus berarti “tiruan burung”. Ia hidup pada akhir Kretasius (70 juta tahun lalu) di  Amerika Utara dan Asia. Untuk menjaga keseimbangan, ia akan menjulurkan  ekornya ke belakang saat berlari. Ekornya separuh panjang tubuhnya. Panjang tubuhnya 3,5-6 m dengan bobot 160 kg. Ia berjalan dengan dua kaki belakangnya  yang panjang langsing. Ia memiliki paruh ompong tanpa gigi. Berkepala kecil dan berleher panjang.  Otak dan matanya yang besar sehingga  ia dianggap cukup cerdas saat berburu dan mencari makanan  Ia pandai berlari kencang karena berotot paha yang kuat  dan tulang kaki belakang yang panjang.",
        "Oviraptor memiliki mulut yg unik. Panjang tubuhnya 2 m dengan bobot 60-100 kg. Ia diperkirakan pemakan daging dan juga Mulutnya tidak bergigi, namun memiliki paruh  tengkorak yang sangat keras. Oviraptor senang mencuri telur. Diperkirakan paruh kerasnya dipakai untuk  menghancurkan kulit telur dan memakan isinya. Fosilnya ditemukan di kumpulan sarang dinosaurus  protoceratop yang penuh telur. Karena itulah ia lalu diberi nama oviraptor, yang berarti  ‘pencuri telur’. Namun ia juga seorang ibu yang baik, karena selalu  duduk di sarangnya menjagai telur-telurnya agar aman  dan tetap hangat sampai menetas. Mahkota di atas kepalanya selain untuk dipamerkan,  juga untuk menghasilkan suara keras dan untuk  mendinginkan otaknya. Mahkota oviraptor berongga dan di dalamnya seperti  sponse, ada rongga pernapasan unik ditutupi dengan  tulang setipis kertas. Dengan mahkota seperti itu membantu  menghangatkan dan melembabkan udara yang  dihirupnya, dan membuat peka penciumannya.",
        "Rinchenia adalah dinosaurus sejenis burung yang hidup  di Mongolia pada akhir zaman Kretasius (89-65 jtl). Rinchenia berjalan dengan dua kaki. Rinchenia memiliki ekor berbulu yang panjang dan  kedua kaki depan yang pendek. Kedua kaki depan rinchenia berbulu dan berbentuk  sayap burung yang berguna untuk menggenggam  makanan. Sebagai alat pertahanan, rinchenia  dilengkapi di setiap jari dan tangannya  cakar lengkung yang tajam. Dinosaurus bertulang ringan ini  panjang tubuhnya  sekitar 2,5 m, tinggi 1,3 m  dengan bobot 40 kg.Fosil rinchenia yang mirip oviraptor  ini ditemukan di Mongolia, Asia. Ia merupakan salah satu pemburu yang gesit. Rinchenia hanya diketahui dari sebuah fosil tunggal  yang terdiri dari tengkorak lengkap dan rahang bawah,  tulang lengan depan, kaki belakang, dan panggul. Meski memiliki lengan dan ekor bersayap seperti  burung namun ia tidak bisa terbang. Kepalanya dihiasi mahkota dari tulang. Mahkota itu digunakan untuk menarik pasangan. Rinchenia diperkirakan masih berhubungan dekat  dengan oviraptor yang juga ditemukan di Mongolia.",
        "Sekitar 70 juta tahun lalu, saurolophus menjelajahi  Benua Asia, Mongolia, dan Amerika Utara.  Saurolophus sejenis dinosaurus pemakan tumbuhan  yang bisa berjalan dengan dua atau empat kaki.  Ia hidup pada periode Cretaceous akhir di Amerika Utara  dan Asia.  Saurolophus Asia bahkan ukurannya lebih besar  dibandingkan saurolophus di Amerika Utara  Panjang tubuh saurolophus sekitar 9,8-12 m dengan  tulang tengkorak sepanjang 1-12 meter.  Bobot saurolophus sekitar 1,9 ton.  Ia memiliki tanduk tabung  udara di atas tengkoraknya,  yang berfungsi untuk  pernapasan dan  pengatur suhu badan.  Untuk berkomunikasi dengan kelompoknya, ia  mengeluarkan suara keras seperti klakson mobil.  Suara itu berasal dari tanduk tabung udara yang  menyokong lipatan kulit di atas hidungnya.  Agar bisa bersuara ia akan menghembuskan udara  lewat lipatan kulit tersebut.  Fosilnya pertama kali ditemukan pada tahun 1911 di  sungai Red Deer di Alberta, kanada.  Dinosaurus berparuh bebek ini memiliki paruh yang  keras.",
        "Spinosaurus memiliki moncong ramping dan panjang  yang mirip buaya sehingga ia dinamai “si rahang buaya”.  Spinosaurus hidup pada akhir zaman Kretasius (89-65  juta tahun lalu) di Mesir dan Maroko.  Spinosaurus merupakan dinosaurus besar pemakan  daging yang memiliki sirip di punggung seperti layar.  Siripnya berguna untuk mengatur suhu tubuh dan  menarik perhatian lawan jenis.   Layar ini mungkin dipenuhi dengan pembuluh darah  yang dapat membantu spinosaurus menghangatkan  dirinya sebelum berburu.  Tulang punggung spinosaurus memuat segumpal  lemak, mirip dengan unta saat ini.   Gumpalan ini membantu melindungi spinosaurus  dari panas dan berfungsi sebagai cadangan makanan.  Meski berjalan dengan dua kaki belakang atau bipedal,  namun spinosaurus pandai berlari kencang.  Besarnya bahkan melebihi tyranosaurus rex dan  giganotosaurus.  Tengkoraknya memiliki panjang hingga 1,5 meter.   Sejak Perang Dunia ke-2, banyak tulang belulang  spinosaurus yang tersimpan di Mesir hancur karena  gempuran pesawat-pesawat pembom.  Ia mencari makanan dengan menyerang dinosaurus  pemakan tumbuhan, memakan bangkai, bahkan  memakan jenisnya sendiri.",
        "Untuk berjalan ke manapun, hampir sepanjang waktu  stegosaurus bertumpu pada keempat kakinya.  Namun saat makan dahan-dahan pohon yang rendah,  stegosaurus bisa duduk bertumpu pada kedua kaki  belakangnya yang kuat.  Stegosaurus berarti ‘kadal beratap’ karena ia memiliki  sisik atau lempengan besar mirip atap di punggungnya.  Ciri utama stegosaurus yang bertubuh sebesar truk itu  adalah dua baris paku atau duri besar di ekornya.  Dua baris paku atau duri tersebut  digunakan sebagai alat pertahanan diri.  Ia akan mengibaskan ekornya itu pada  lawannya.  Otak stegosaurus ternyata sangat  kecil sekali.   Otaknya hanya sebesar bola golf.  Saking kecilnya otak itu, para  ilmuwan pun mengira kalua stegosaurus memiliki otak lain di pinggulnya.  Dinosaurus berpelindung yang paling terkenal ini hidup  pada akhir periode Jurasik (156-140 juta tahun lalu) di  bagian barat tengah Amerika Serikat.  Stegosaurus memiliki dua baris lempengan atau atap  yang unik di punggungnya.  Lempengan itu dilapisi kulit dan tanduk yang berguna  untuk alat pertahanan dan menghangatkan tubuhnya  jika kedinginan.",
        "Therizinosaurus memiliki cakar yang mirip kura-kura.  Panjang cakar belatinya yang tidak ditutupi daging  mencapai 90 cm dengan panjang keseluruhan 1,5 m.  Therizinosaurus hidup pada akhir zaman Cretasius (89- 65 juta tahun lalu) di Mongolia, Cina, Amerika Utara.  Ia jenis dinosaurus pemakan tumbuhan yang ditemukan  oleh Maleev pada tahun 195   Cakar raksasa therizinosaurus berguna  untuk meraih ranting pohon saat makan.   Cakar ini juga berguna untuk melawan  pemangsa dan sebagai perlindungan diri.  Semula palaeontolog mengira therizinosaurus  sejenis dinosaurus pemakan daging, saat  menemukan fosil lengannya di Mongolia.   Tapi, kemudian palaeontolog menemukan fosil  utuh yang struktur giginya sama sekali tidak mirip  dinosaurus pemakan daging.   Setelah ditemukan bagian kepala serta giginya palaeontolog dengan yakin menggolongkannya sebagai  dinosaurus pemakan tumbuhan.   Kepala dan giginya kecil, sama seperti tumbuhan  pemakan daun lainnya.   Palaeontolog pun menduga kalau ia merupakan  dinosaurus evolusi dari dinosaurus pemakan daging  yang menjadi dinosaurus pemakan tumbuhan.  Cakar besarnya berguna untuk meraih ranting pohon  saat makan, melawan pemangsa, dan sangat berguna  sebagai perlindungan diri.",
        "Troodon adalah dinosaurus paling pintar karena ia  memiliki otak paling besar dibanding dinosaurus  lainnya.  Tubuhnya kecil mirip burung.  Fosilnya ditemukan pada tahun 1855 di Amerika Utara.  Troodon berarti ‘gigi terluka’ merujuk pada giginya yang  bergerigi tajam dan panjang.   Dinosaurus ini sebelumnya disebut saurornithoidida.  Troodon hidup di akhir Zaman Kretasius (89-65 juta  tahun lalu) di Amerika Utara.  Troodon memiliki pendengaran dan penciuman  yang tajam sehingga ia banyak ditakuti lawannya.  Rahangnya panjang dan ramping.  Pemakan daging kecil ini panjang tubuhnya 2,5 meter.  Troodon hidup berkelompok seperti velociraptor.  Dalam satu kelompok biasanya terdiri dari satu  keluarga.   Troodon muda sering tidak ikut berburu mangsa, ia hanya menunggu di sarangnya.  Troodon memiliki lengan yang bisa memegang sesuatu.",
        "Tyrannosaurus merupakan salah satu hewan pemburu  terbesar dan terbuas yang pernah hidup di darat.   Panjangnya melebihi 15 m, tinggi 5 m, dan berat 7 ton.  Ia bisa memangsa dinosaurus pemakan tumbuhan  terbesar saat itu, seperti triceratops dan edmontosaurus.  Gigi tyrannosaurus tampak seperti gergaji karena  bergerigi, tebal, setajam silet, dan kuat.  Saking kuatnya, giginya bisa mengunyah dan  meremukkan tulang.  Tyrannosaurus memiliki 60 gigi dan jika masih hidup  sekarang bisa menjadi pemangsa terbuas yang bisa  menelan manusia.  Giginya besar-besar dengan panjang 15  cm.  Meskipun tubuh dan kepalanya  besar, tapi tangan atau  lengannya amat kecil.  Kedua lengan depan itu berguna untuk mencengkeram  mangsa dan untuk bangkit dari tanah saat berbaring.  Ia dapat berlari hingga 70 km/jam.  Letak mata di kepalanya mirip dengan serigala.  Ia diduga berperilaku seperti buaya dan reptil modern  lainnya, karena bentuk otaknya amat mirip dengan  buaya dan aligator.  Kedua lengan depan itu berguna untuk mencengkeram  mangsa dan untuk bangkit dari tanah saat berbaring.  Ia dapat berlari hingga 70 km/jam.  Letak mata di kepalanya mirip dengan serigala.  Ia diduga berperilaku seperti buaya dan reptil modern  lainnya, karena bentuk otaknya amat mirip dengan  buaya dan aligator.",
        "Velociraptor selalu mengangkat cakarnya di atas tanah  agar siap digunakan setiap saat.  Senjata berupa cakar di tangan dan kaki velociraptor itu  merupakan senjata andalan.  Meskipun panjang-panjang, namun cakar jari  velociraptor dapat dilipat sampai 180 derajat.  Ukuran velociraptor kecil, namun ia terkenal pintar  sehingga ia bisa bersaing hidup dengan predator besar  yang hidup di tempat yang sama.  Ia juga sangat mematikan seperti tyrannosaurus.  Larinya cepat dan gesit saat memangsa  anak dinosaurus dan mamalia kecil.  Selain memakan daging, ia juga  suka mencuri telur dinosaurus  yang lain jika tidak ada mangsa.  Velociraptor hampir mirip  tyrannosaurus, bedanya  ia senang hidup berkelompok dan berukuran lebih kecil.  Panjang tubuhnya sekitar 1,5 meter, tinggi  meter, dan  berat sekitar 7-14 kilogram.  Velociraptor hidup pada akhir zaman Kretasius (89-65  juta tahun lalu).  Ia dan kelompoknya suka mengalihkan perhatian  mangsa yang sudah mereka kepung.  Fosilnya ditemukan di daerah Mongolia, Rusia, dan Cina.  Ia memiliki sebuah  cakar besar melengkung.  Cakar itu untuk menusuk atau merobek mangsanya.  Ia juga suka menyerang mangsanya dengan kuku  kakinya yang tajam.")

    private val dinoImages = intArrayOf(
        R.drawable.ornithomimus,
        R.drawable.oviraptor,
        R.drawable.rinchenia,
        R.drawable.saurolophus,
        R.drawable.spinosaurus,
        R.drawable.stegosaurus,
        R.drawable.therizinosaurus,
        R.drawable.troodon,
        R.drawable.tyrannosaurus,
        R.drawable.velociraptor
    )

    val listData: ArrayList<Dino>
    get() {
        val list = arrayListOf<Dino>()
        for (position in dinoNames.indices) {
            val dino = Dino()
            dino.name = dinoNames[position]
            dino.detail = dinoDetails[position]
            dino.photo = dinoImages[position]
            list.add(dino)
        }
        return list
    }
}